#pragma once

#include "ITerrainLoader.h"

namespace Ogre
{
	class Image;
}

namespace FlagRTS
{
	// Load map using : heightmap and blend maps generated by Artefix editor
	class ArtefixTerrainLoader : public ITerrainLoader
	{

	public:
		ArtefixTerrainLoader(TerrainGrid*, TerrainInfo&);

		void LoadTerrain();

		void UnloadTerrain();

	private:
		void LoadTerrainHeightMap(const string& mapname, uint8 x, uint8 y, Ogre::Image* img);
		void DefineTerrain(int x, int z);
		void InitBlendMaps(int x, int z);
	};
}