#pragma once

#include "DataTypes.h"

namespace Ogre
{
	class Image;
}

namespace FlagRTS
{
	class OgreTerrainGrid;
	class TerrainInfo;

	// Load map using : heightmap and blend maps generated by Artefix editor
	class OgreTerrainLoader
	{
		OgreTerrainGrid* _terrainGrid;
		TerrainInfo* _terrainInfo;

	public:
		OgreTerrainLoader(OgreTerrainGrid*, TerrainInfo*);

		void LoadTerrain();
		void UnloadTerrain();

	private:
		void LoadTerrainHeightMap(const string& mapname, uint8 x, uint8 y, Ogre::Image* img);
		void DefineTerrain(int x, int z);
		void InitBlendMaps(int x, int z);
	};
}